<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ef2f2853-42ec-41ff-81ee-c56fb3a85d0f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Livekit.Server.Sdk.Dotnet" Version="1.2.3" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
  </ItemGroup>

</Project>
